# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name_plural': '答案表'},
        ),
        migrations.AlterModelOptions(
            name='classlist',
            options={'verbose_name_plural': '班级表'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name_plural': '单选题的选项'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': '问题表'},
        ),
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'verbose_name_plural': '问卷表'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '学生表'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Student', verbose_name='谁回答的'),
        ),
    ]
