# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20171206_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='take_part_num',
            new_name='stu_num',
        ),
    ]
