# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-29 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20171207_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'\xe7\xad\x94\xe6\xa1\x88\xe5\x86\x85\xe5\xae\xb9'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Question', verbose_name=b'\xe9\x97\xae\xe9\xa2\x98'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Student', verbose_name=b'\xe8\xb0\x81\xe5\x9b\x9e\xe7\xad\x94\xe7\x9a\x84'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='title',
            field=models.CharField(max_length=16, verbose_name=b'\xe7\x8f\xad\xe7\xba\xa7\xe5\x90\x8d'),
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=32, verbose_name=b'\xe9\x80\x89\xe9\xa1\xb9\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AlterField(
            model_name='option',
            name='score',
            field=models.IntegerField(verbose_name=b'\xe9\x80\x89\xe9\xa1\xb9\xe5\xaf\xb9\xe5\xba\x94\xe7\x9a\x84\xe5\x88\x86\xe5\x80\xbc'),
        ),
        migrations.AlterField(
            model_name='question',
            name='caption',
            field=models.CharField(max_length=64, verbose_name=b'\xe9\x97\xae\xe9\xa2\x98\xe6\xa0\x87\xe9\xa2\x98'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ct',
            field=models.IntegerField(choices=[(1, b'\xe6\x89\x93\xe5\x88\x86'), (2, b'\xe5\x8d\x95\xe9\x80\x89'), (3, b'\xe8\xaf\x84\xe4\xbb\xb7')]),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='cls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.ClassList', verbose_name=b'\xe8\xb0\x83\xe6\x9f\xa5\xe7\x8f\xad\xe7\xba\xa7'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo', verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe8\x80\x85'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='stu_num',
            field=models.IntegerField(default=0, verbose_name=b'\xe5\x8f\x82\xe4\xb8\x8e\xe4\xba\xba\xe6\x95\xb0'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='title',
            field=models.CharField(max_length=128, verbose_name=b'\xe9\x97\xae\xe5\x8d\xb7\xe6\xa0\x87\xe9\xa2\x98'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.ClassList', verbose_name=b'\xe6\x89\x80\xe5\x9c\xa8\xe7\x8f\xad\xe7\xba\xa7'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=16, verbose_name=b'\xe5\xad\xa6\xe7\x94\x9f\xe5\xa7\x93\xe5\x90\x8d'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pwd',
            field=models.CharField(max_length=16, verbose_name=b'\xe5\xaf\x86\xe7\xa0\x81'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=16, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\xaf\x86\xe7\xa0\x81'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=16, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d'),
        ),
    ]
